database:
  db: "article.db"
  table: "article"
mail:
  host: "smtp.163.com"
  port: 25
  user: "15512134812@163.com"
  pass: "xxxxxxxx"
qiniu:
  accessKey: "accessKey"
  secretKey: "secretKey"
  bucket: "bucket"
  limit: 2